### ISSUE TITLE
ImportError: No module named 'six'

### ISSUE THREAD

**Issue by sddzlsc** [Kainmueller-Lab/PatchPerPix_experiments#7]
(tf_35) [s-lishoucong@admin1 PatchPerPix_experiments]$ python run_ppp.py --setup setup08 --config wormbodies/02_setups/setup08/config.toml --do mknet train validate_checkpoints predict decode label evaluate --app wormbodies --root ~/data/patchPerPix/experiments
No module named 'six'
Traceback (most recent call last):
  File "run_ppp.py", line 41, in <module>
    import h5py
  File "/mnt/public/home/s-lishoucong/anaconda3/envs/tf_35/lib/python3.5/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
  File "h5py/_errors.pyx", line 13, in init h5py._errors
  File "/mnt/public/home/s-lishoucong/anaconda3/envs/tf_35/lib/python3.5/site-packages/h5py/_hl/compat.py", line 5, in <module>
    import six
ImportError: No module named 'six'

**Comment by abred** [comment]
Hi,
thanks for posting this issue, it seems to be a problem of the h5py package though, as that is trying to `import six`. Maybe something went wrong when you tried to install the `requirements.txt`. Should be easily fixable by installing six manually with pip.
