### ISSUE TITLE
RuntimeError: child process died at the 'predict_sample' task level 

### ISSUE THREAD

**Issue by pietramarrone** [Kainmueller-Lab/PatchPerPix_experiments#9]
Hi, the model with setup08 for wormbodies trains all the way to the end, but as soon as it gets to the prediction task the process dies. The model is running inside an instance on SageMaker.

Here below the error: 

```
INFO:wormbodies.02_setups.setup08.train:Batch: iteration=9999, time=2.851346
INFO:gunpowder.producer_pool:terminating workers...
INFO:gunpowder.producer_pool:joining workers...
INFO:gunpowder.producer_pool:done
Training finished
INFO:__main__:time train: 2:25:17.521035
INFO:__main__:validating all checkpoints
{'general': {'logging': 20, 'debug': False, 'overwrite': False}, 'data': {'train_data': '/home/ec2-user/SageMaker/train_test_split/train', 'val_data': '/home/ec2-user/SageMaker/train_test_split/test', 'test_data': '/home/ec2-user/SageMaker/train_test_split/test', 'voxel_size': [1, 1], 'input_format': 'zarr', 'raw_key': 'volumes/raw_bf', 'gt_key': 'volumes/gt_instances', 'one_instance_per_channel_gt': 'volumes/gt_labels', 'num_channels': 1, 'validate_on_train': False}, 'model': {'train_net_name': 'train_net', 'test_net_name': 'test_net', 'train_input_shape': [256, 256], 'test_input_shape': [512, 512], 'patchshape': [1, 41, 41], 'patchstride': [1, 1, 1], 'num_fmaps': 40, 'max_num_inst': 2, 'fmap_inc_factors': [2, 2, 2, 2], 'fmap_dec_factors': [1, 1, 1, 1], 'downsample_factors': [[2, 2], [2, 2], [2, 2], [2, 2]], 'activation': 'relu', 'padding': 'valid', 'kernel_size': 3, 'num_repetitions': 2, 'upsampling': 'resize_conv', 'overlapping_inst': True, 'code_units': 252, 'autoencoder_chkpt': 'this'}, 'optimizer': {'optimizer': 'Adam', 'lr': 0.0001}, 'preprocessing': {'clipmax': 1500}, 'training': {'batch_size': 1, 'num_gpus': 2, 'num_workers': 10, 'cache_size': 40, 'max_iterations': 10000, 'checkpoints': 5000, 'snapshots': 2000, 'profiling': 500, 'train_code': True, 'sampling': {'min_masked': 0.001, 'min_masked_overlap': 0.0001, 'overlap_min_dist': 0, 'overlap_max_dist': 15, 'probability_overlap': 0.5, 'probability_fg': 0.5}, 'augmentation': {'elastic': {'control_point_spacing': [10, 10], 'jitter_sigma': [1, 1], 'rotation_min': -45, 'rotation_max': 45}, 'intensity': {'scale': [0.9, 1.1], 'shift': [-0.1, 0.1]}, 'simple': {}}}, 'prediction': {'output_format': 'zarr', 'aff_key': 'volumes/pred_affs', 'code_key': 'volumes/pred_code', 'fg_key': 'volumes/pred_numinst', 'fg_thresh': 0.5, 'decode_batch_size': 1024}, 'validation': {}, 'testing': {'num_workers': 5}, 'vote_instances': {'patch_threshold': 0.9, 'fc_threshold': 0.5, 'cuda': True, 'blockwise': False, 'num_workers': 8, 'chunksize': [92, 92, 92], 'select_patches_for_sparse_data': True, 'save_no_intermediates': True, 'output_format': 'hdf', 'parallel': False, 'includeSinglePatchCCS': True, 'sample': 1.0, 'removeIntersection': True, 'mws': False, 'isbiHack': False, 'mask_fg_border': False, 'graphToInst': False, 'skipLookup': False, 'skipConsensus': False, 'skipRanking': False, 'skipThinCover': True, 'affinity_graph_voting': False, 'affinity_graph_voting_selected': False, 'termAfterThinCover': False, 'fg_thresh_vi': 0.1, 'consensus_interleaved_cnt': False, 'consensus_norm_prob_product': True, 'consensus_prob_product': True, 'consensus_norm_aff': True, 'vi_bg_use_inv_th': False, 'vi_bg_use_half_th': False, 'vi_bg_use_less_than_th': True, 'rank_norm_patch_score': True, 'rank_int_counter': False, 'patch_graph_norm_aff': True, 'blockwise_old_stitch_fn': False, 'only_bb': False, 'flip_cons_arr_axes': False, 'return_intermediates': False}, 'evaluation': {'num_workers': 1, 'res_key': 'vote_instances', 'metric': 'confusion_matrix.th_0_5.AP'}, 'postprocessing': {'remove_small_comps': 600, 'watershed': {'output_format': 'hdf'}}, 'visualize': {'samples_to_visualize': ['A10', 'C17'], 'show_patches': True}, 'autoencoder': {'train_net_name': 'train_net', 'test_net_name': 'test_net', 'train_input_shape': [1, 41, 41], 'test_input_shape': [1, 41, 41], 'patchshape': [1, 41, 41], 'patchstride': [1, 1, 1], 'network_type': 'conv', 'activation': 'relu', 'code_activation': 'sigmoid', 'encoder_units': [500, 1000], 'decoder_units': [1000, 500], 'num_fmaps': [32, 64, 128], 'downsample_factors': [[2, 2], [2, 2], [2, 2]], 'upsampling': 'resize_conv', 'kernel_size': 3, 'num_repetitions': 2, 'padding': 'same', 'code_method': 'conv1x1', 'code_units': 252, 'regularizer': 'l2', 'regularizer_weight': 0.0001, 'loss_fn': 'mse', 'overlapping_inst': False}, 'base': '/home/ec2-user/SageMaker/experiments/wormbodies_setup08_211019_142458'}
INFO:__main__:validating checkpoint 5000 {}
INFO:__main__:predicting checkpoint 5000
INFO:__main__:reading data from /home/ec2-user/SageMaker/train_test_split/test
['D06', 'E03', 'C19', 'D02', 'E04', 'D07', 'C24', 'C15', 'C13', 'D16', 'D12', 'D14', 'C17', 'C21', 'D17', 'C10', 'C05', 'D03', 'D21', 'D23', 'C08', 'C09', 'D13', 'D04', 'C20', 'D05', 'D09', 'C18', 'D20', 'D24', 'D11', 'C22', 'E02', 'C07', 'C14', 'D22', 'C16', 'D18', 'C23', 'D01', 'D15', 'E01', 'C11', 'D19', 'C12', 'C04', 'C06', 'D10', 'D08', 'C03']
['D06', 'E03', 'C19', 'D02', 'E04', 'D07', 'C24', 'C15', 'C13', 'D16', 'D12', 'D14', 'C17', 'C21', 'D17', 'C10', 'C05', 'D03', 'D21', 'D23', 'C08', 'C09', 'D13', 'D04', 'C20', 'D05', 'D09', 'C18', 'D20', 'D24', 'D11', 'C22', 'E02', 'C07', 'C14', 'D22', 'C16', 'D18', 'C23', 'D01', 'D15', 'E01', 'C11', 'D19', 'C12', 'C04', 'C06', 'D10', 'D08', 'C03']
INFO:__main__:forking <function predict_sample at 0x7f6a97b227a0>
INFO:__main__:predicting D06!
Traceback (most recent call last):
  File "run_ppp.py", line 1603, in <module>
    main()
  File "run_ppp.py", line 1474, in main
    output_folder)
  File "run_ppp.py", line 751, in validate_checkpoints
    output_folder)
  File "run_ppp.py", line 107, in wrapper
    ret = func(*args, **kwargs)
  File "run_ppp.py", line 669, in validate_checkpoint
    checkpoint_file, test_folder, pred_folder)
  File "run_ppp.py", line 107, in wrapper
    ret = func(*args, **kwargs)
  File "run_ppp.py", line 548, in predict
    test_folder, output_folder)
  File "run_ppp.py", line 123, in wrapper
    raise RuntimeError("child process died")
RuntimeError: child process died
```

Any clue of what this could mean?

Thanks!

**Comment by abred** [comment]
Hi,

before `predict_sample` is called the process is forked (has some tensorflow reasons, we had some problems otherwise) but it seems the error message for whatever errors is thrown within it is hidden. Could you please try to wrap the call to `predict_fn`
https://github.com/Kainmueller-Lab/PatchPerPix_experiments/blob/3517172cf0a3962a033057b6813397b99f5a20e3/run_ppp.py#L475 in a try except block
```
try:
  predict_fn(...)
except Exception e:
  print(e)
  raise e
```
and let me know if there is a more informative error message?
thanks!

**Comment by pietramarrone** [comment]
Hi, thanks a lot for your reply. Placing that bit  of code around predict_fn doesn't catch any error. I have investigated a bit the `predict.py` function in the setup08 folder and it appears that it runs through until the pipeline is built. I have enclosed the pipeline in a try/except condition as follows (the 4 print statements were added just to check the parms read into gp.tensorflow.Predict):

```
print(os.path.join(kwargs['input_folder'], name + '.meta'))
print(kwargs['checkpoint'])
print(net_names['raw'])
print(outputs)
try:
    pipeline = (
        source +
        gp.Pad(raw, context) +
        gp.IntensityScaleShift(raw, 2, -1) +

        # perform one training iteration for each passing batch (here we use
        # the tensor names earlier stored in train_net.config)
        gp.tensorflow.Predict(
            graph=os.path.join(kwargs['input_folder'], name + '.meta'),
            checkpoint=kwargs['checkpoint'],
            inputs={
                net_names['raw']: raw
            },
            outputs=outputs) +

        # store all passing batches in the same HDF5 file
        gp.ZarrWrite(
            outVolumes,
            output_dir=kwargs['output_folder'],
            output_filename=kwargs['sample'] + ".zarr",
            compression_type='gzip'
        ) +

        # show a summary of time spend in each node every 10 iterations
        gp.PrintProfilingStats(every=10) +

        # iterate over the whole dataset in a scanning fashion, emitting
        # requests that match the size of the network
        gp.Scan(reference=request)
    )
except Exception as e:
    print(e)
    raise e
print('here')
```

but again, no specific error message thrown, just this:

```
INFO:__main__:predicting D07!
../experiments/wormbodies_setup08_211019_142458/test/test_net.meta
../experiments/wormbodies_setup08_211019_142458/train/train_net_checkpoint_5000
raw:0
{'Sigmoid:0': PRED_AFFS, 'transpose_9:0': PRED_NUMINST}
Traceback (most recent call last):
  File "run_ppp.py", line 1608, in <module>
    main()
  File "run_ppp.py", line 1479, in main
    output_folder)
  File "run_ppp.py", line 756, in validate_checkpoints
    output_folder)
  File "run_ppp.py", line 107, in wrapper
    ret = func(*args, **kwargs)
  File "run_ppp.py", line 674, in validate_checkpoint
    checkpoint_file, test_folder, pred_folder)
  File "run_ppp.py", line 107, in wrapper
    ret = func(*args, **kwargs)
  File "run_ppp.py", line 553, in predict
    test_folder, output_folder)
  File "run_ppp.py", line 123, in wrapper
    raise RuntimeError("child process died")
RuntimeError: child process died
```

Anything else I could do to help you diagnose the problem?

Thanks a lot!

**Comment by abred** [comment]
Could you try printing the p.exitcode here:
https://github.com/Kainmueller-Lab/PatchPerPix_experiments/blob/3517172cf0a3962a033057b6813397b99f5a20e3/run_ppp.py#L122-L123
Maybe that gives us a clue.

Additionally you could try removing the `@fork` here temporarily
https://github.com/Kainmueller-Lab/PatchPerPix_experiments/blob/3517172cf0a3962a033057b6813397b99f5a20e3/run_ppp.py#L460

**Comment by pietramarrone** [comment]
So without commenting out `@fork` the p.exitcode is this one:

```
INFO:__main__:predicting C24!
../experiments/wormbodies_setup08_211019_142458/test/test_net.meta
../experiments/wormbodies_setup08_211019_142458/train/train_net_checkpoint_5000
raw:0
{'Sigmoid:0': PRED_AFFS, 'transpose_9:0': PRED_NUMINST}
-7
Traceback (most recent call last):
  File "run_ppp.py", line 1609, in <module>
    main()
  File "run_ppp.py", line 1480, in main
```

when I also comment out `@fork` it p.exitcode returns this:

```
INFO:__main__:predicting C15!
Bus error
```

Edit: I also attach the packages version file
[pkg_versions.txt](https://github.com/Kainmueller-Lab/PatchPerPix_experiments/files/7380269/pkg_versions.txt)

**Comment by abred** [comment]
ah ok, so it's related to your machine, I think this sometimes happens if there is not enough memory/RAM. I am not familiar with SageMaker, maybe you can allocate more there?. Otherwise you could try to add `max_shared_memory=0.2*1024*1024*1024` to the call here:
https://github.com/Kainmueller-Lab/PatchPerPix_experiments/blob/3517172cf0a3962a033057b6813397b99f5a20e3/wormbodies/02_setups/setup08/predict.py#L119-L125
(try varying the `0.2`, the default is `1.0` (=1GB), depending on the sample size less might still be sufficient)

**Comment by pietramarrone** [comment]
Thanks a lot for the suggestion. I have done as you suggested (using 0.5) and it worked until this point below, where it throws the following error:

```
INFO:__main__:reading data from ../experiments/wormbodies_setup08_211019_142458/val/processed/5000
['D06', 'E03', 'C19', 'D02', 'E04', 'D07', 'C24', 'C15', 'C13', 'D16', 'D12', 'D14', 'C17', 'C21', 'D17', 'C10', 'C05', 'D03', 'D21', 'D23', 'C08', 'C09', 'D13', 'D04', 'C20', 'D05', 'D09', 'C18', 'D20', 'D24', 'D11', 'C22', 'E02', 'C07', 'C14', 'D22', 'C16', 'D18', 'C23', 'D01', 'D15', 'E01', 'C11', 'D19', 'C12', 'C04', 'C06', 'D10', 'D08', 'C03']
['D06', 'E03', 'C19', 'D02', 'E04', 'D07', 'C24', 'C15', 'C13', 'D16', 'D12', 'D14', 'C17', 'C21', 'D17', 'C10', 'C05', 'D03', 'D21', 'D23', 'C08', 'C09', 'D13', 'D04', 'C20', 'D05', 'D09', 'C18', 'D20', 'D24', 'D11', 'C22', 'E02', 'C07', 'C14', 'D22', 'C16', 'D18', 'C23', 'D01', 'D15', 'E01', 'C11', 'D19', 'C12', 'C04', 'C06', 'D10', 'D08', 'C03']
['D06', 'E03', 'C19', 'D02', 'E04', 'D07', 'C24', 'C15', 'C13', 'D16', 'D12', 'D14', 'C17', 'C21', 'D17', 'C10', 'C05', 'D03', 'D21', 'D23', 'C08', 'C09', 'D13', 'D04', 'C20', 'D05', 'D09', 'C18', 'D20', 'D24', 'D11', 'C22', 'E02', 'C07', 'C14', 'D22', 'C16', 'D18', 'C23', 'D01', 'D15', 'E01', 'C11', 'D19', 'C12', 'C04', 'C06', 'D10', 'D08', 'C03']
INFO:__main__:forking <function vote_instances_sample_seq at 0x7f06ee1f9950>
INFO:PatchPerPix.vote_instances.vote_instances:processing ../experiments/wormbodies_setup08_211019_142458/val/processed/5000/D06.zarr
INFO:PatchPerPix.vote_instances.utilVoteInstances:keys: ['volumes']
INFO:PatchPerPix.vote_instances.vote_instances:affinities shape: (1681, 1, 520, 696)
INFO:PatchPerPix.vote_instances.vote_instances:numinst_ shape: (3, 1, 520, 696)
INFO:PatchPerPix.vote_instances.vote_instances:input image shape: (1, 520, 696)
INFO:PatchPerPix.vote_instances.vote_instances:Number fg pixel: 12742
INFO:PatchPerPix.vote_instances.vote_instances:overlap mask: (1, 520, 696) 1
INFO:PatchPerPix.vote_instances.vote_instances:copy fg to fg2cover
INFO:PatchPerPix.vote_instances.vote_instances:Number overlapping pixel: 1
INFO:PatchPerPix.vote_instances.vote_instances:Number pixel fg_to_cover: 12742
INFO:PatchPerPix.vote_instances.vote_instances:num foreground pixels: 12742
INFO:PatchPerPix.vote_instances.vote_instances:num foreground pixels 12742
INFO:PatchPerPix.vote_instances.vote_instances:num foreground pixels excluding boundary region: 12742
INFO:PatchPerPix.vote_instances.utilVoteInstances:bg in rank: <th
INFO:PatchPerPix.vote_instances.utilVoteInstances:ignoring overlap in consensus computation
INFO:PatchPerPix.vote_instances.utilVoteInstances:accumulate normalized prob product [0,1] as aff
INFO:PatchPerPix.vote_instances.consensus_array:compute affs and cntr separately
/home/ec2-user/SageMaker/conda-envs/custom_ppp_env/lib/python3.7/site-packages/pycuda/compiler.py:588: UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu(31): warning: pointless comparison of unsigned integer with zero


  self.add_source(source, nvcc_options=options)
-9
Traceback (most recent call last):
  File "run_ppp.py", line 1609, in <module>
    main()
  File "run_ppp.py", line 1480, in main
    output_folder)
  File "run_ppp.py", line 757, in validate_checkpoints
    output_folder)
  File "run_ppp.py", line 107, in wrapper
    ret = func(*args, **kwargs)
  File "run_ppp.py", line 691, in validate_checkpoint
    vote_instances(args, config, data, pred_folder, inst_folder)
  File "run_ppp.py", line 107, in wrapper
    ret = func(*args, **kwargs)
  File "run_ppp.py", line 812, in vote_instances
    output_folder, sample)
  File "run_ppp.py", line 124, in wrapper
    raise RuntimeError("child process died")
RuntimeError: child process died
```

Edit: it is probably worth mentioning that I **trained the model for 10000 iterations only**, to test it end-to-end before training it with the default settings (400000 iterations). I can see there is `INFO:PatchPerPix.vote_instances.vote_instances:Number overlapping pixel: 1` and don't know whether this can contribute in generating the error. Also let me know if it's worth opening a separate issue for this specific problem, I can reference it there.

**Comment by abred** [comment]
iirc -9 refers to SIGKILL, which often indicates insufficient memory, too (thus we can keep it in this issue).
That's one issue with PatchPerPix, it needs quite a bit of memory. As you can see in the log output the affinities array has size: `INFO:PatchPerPix.vote_instances.vote_instances:affinities shape: (1681, 1, 520, 696)`
What kind of machine do you have access to in SageMaker (RAM, GPU)?
Have you changed anything in the config file? Please make sure that `num_parallel_samples` is either not set or set to `1` under `[vote_instances]`

**Comment by pietramarrone** [comment]
the GPU I am using is:

Architecture:  Turing   
NVIDIA GPU: T4
Instance type: G4
Instance size: g4dn.xlarge 
Number of GPUs: 1
GPU Interconnect: PCIe
GPU Memory: 16 GB
Tensorcores : gen 2   

would I need more in principle?

I confirm I do not have `num_parallel_samples` set under `[vote_instances]`. I have `num_workers = 8` though, should I reduce this value?

**Comment by abred** [comment]
I think `num_workers` is a leftover from a previous version, you can try it but I don't think it is used anymore.
The GPU looks fine, the issue might be the amount of main memory, I just googled g4dn.xlarge and it seems to have 16GB of RAM, which might be a bit low. If it is an option for you, could you please try one with more memory and see if that solves the problem? If it does I see two options: keep using a larger machine or try to lower the memory usage of the code. Unfortunately we did not optimize the code in that regard. There might be some unnecessary or redundant copies of numpy arrays in there

**Comment by pietramarrone** [comment]
Sure I can try to switch to a different instance, how much RAM do you think I would need in principle (on the wormbodies dataset)? If I get this up and running then I can make all the changes to my own data by slicing the samples etc... 
Also a quick and rather trivial question: based on the error I got, from which step of the pipeline below should I restart the run? 

```
python run_ppp.py --setup setup08 --config ../experiments/wormbodies_setup08_211019_142458/config.toml --do validate_checkpoints predict decode label evaluate --app wormbodies -id ../experiments/wormbodies_setup08_211019_142458
```

Thank you!

**Comment by abred** [comment]
I'm not sure unfortunately, I'd suggest just trying larger ones, step by step, but should not be that much for this data.

Regarding the second question, in principle the pipeline should just skip steps that have already been computed before, so it's not that relevant.
validate_checkpoints executes predict, decode, label, evaluate on the validation set (in that order).
predict, decode, label and evaluate just refer to the test set.
(validation and test sets are defined in the config file)
The error you're getting at the moment happens in the label step (within validate_checkpoints).
(For just getting the pipeline to run it might, in general, be easier to not use validate_checkpoints but the separate steps on the test set, but as you've already computed the predictions for the samples in the validation set it might be better to just continue as is)

**Comment by pietramarrone** [comment]
Ok perfect, thanks for clarifying! 

Re the GPU, would 2 GPUs of 16GB RAM each be a good starting point? Just asking beforehand to avoid burning money if this is not a good setup anyways.

Thanks a lot for all the help!

**Comment by abred** [comment]
The GPU is fine, it's more about the main memory of the machine.

You could also, for example, add an `exit()` statement at the end of the function https://github.com/Kainmueller-Lab/PatchPerPix_experiments/blob/3517172cf0a3962a033057b6813397b99f5a20e3/run_ppp.py#L819
so that only a single sample is processed. If one sample works, the others will likely work as well.

**Comment by pietramarrone** [comment]
I have added the exit statement at the bottom here:

```
def vote_instances_sample(args, config, data, pred_folder, output_folder,
                          sample):
    if config['data'].get('sub_folders', False):
        config['vote_instances']['result_folder'] = \
            os.path.join(output_folder,
                         os.path.basename(os.path.dirname(sample)))
    else:
        config['vote_instances']['result_folder'] = output_folder

    if args.term_after_patch_graph:
        config['vote_instances']['termAfterPatchGraph'] = True
    if args.graph_to_inst:
        config['vote_instances']['graphToInst'] = True

    # check if instance file already exists
    output_fn = os.path.join(
        config['vote_instances']['result_folder'],
        os.path.basename(sample) + '.' + config['vote_instances']['output_format'])
    if not config['general']['overwrite'] and os.path.exists(output_fn):
        if check_file(output_fn, remove_on_error=False,
                      key=config['evaluation']['res_key']):
            logger.info('Skipping vote instances for %s. Already exists!',
                        sample)
            return
        else:
            logger.info('vote instances %s broken. recomputing..!', sample)

    if config['vote_instances']['cuda'] and \
       'CUDA_VISIBLE_DEVICES' not in os.environ and \
       not config['vote_instances'].get('graphToInst', False):
        raise RuntimeError("no free GPU available!")

    if config['vote_instances']['cuda'] and \
        not config['vote_instances']['blockwise']:
        if config['vote_instances'].get("num_parallel_samples", 1) == 1:
            config['vote_instances']['mutex'] = multiprocessing.Lock()
        else:
            config['vote_instances']['mutex'] = mutex

    if config['vote_instances']['blockwise']:
        pred_file = os.path.join(
            pred_folder, sample + '.' + config['prediction']['output_format'])
        if config['vote_instances']['blockwise_old_stitch_fn']:
            fn = vi.ref_vote_instances_blockwise.main
        else:
            fn = vi.stitch_patch_graph.main
        fn(pred_file,
           **config['vote_instances'],
           **config['model'],
           **config['visualize'],
           aff_key=config['prediction'].get('aff_key'),
           fg_key=config['prediction'].get('fg_key'),
           )
    else:
        config['vote_instances']['affinities'] = os.path.join(
            pred_folder, sample + '.' + config['prediction'][
                'output_format'])
        vi.vote_instances.main(
            **config['vote_instances'],
            **config['model'],
            debug=config['general']['debug'],
            aff_key=config['prediction'].get('aff_key'),
            fg_key=config['prediction'].get('fg_key'),
            )
    sys.exit()
```

but still getting the same error unfortunately.

**Comment by abred** [comment]
sorry, I meant in combination with a larger machine, just for testing to "burn" less money.

**Comment by pietramarrone** [comment]
ah ok sorry I misunderstood, ok will try it out thank you! Will keep you updated :)

**Comment by pietramarrone** [comment]
An instance with 64GB RAM is doing the job, thanks a lot for your help! 

I was also testing setup10 for wormbodies but got an error from a key in the config file, will open another issue for that another time. Congratulations with the approach btw, it's very elegant. 

Will close this issue then.
